volumes:
  ollama-data:

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./start_ollama.sh:/start_ollama.sh
      - ollama-data:/root/.ollama
    entrypoint: ["sh", "/start_ollama.sh"]

  app:
    build:
      context: .
    container_name: aws-llm
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./data:/app/data
